// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Deposit")]
public partial class Deposit
{
    [Key]
    [Column("DepositID")]
    public int DepositId { get; set; }

    [Column("OrderID")]
    public int? OrderId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? DepositAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateDeposited { get; set; }

    [StringLength(15)]
    public string DepositStatus { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Deposits")]
    public virtual RentalOrder Order { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Deposits")]
    public virtual User User { get; set; }
}