// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("MembershipPolicy")]
public partial class MembershipPolicy
{
    [Key]
    [Column("MembershipPolicyID")]
    public int MembershipPolicyId { get; set; }

    [StringLength(50)]
    public string LevelName { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MinRentalAmount { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? MaxRentalAmount { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? DiscountPercentage { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? FreeShippingThreshold { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? VoucherAmount { get; set; }

    [StringLength(255)]
    public string FreeRentalDescription { get; set; }

    [StringLength(255)]
    public string BirthdayGiftDescription { get; set; }

    [InverseProperty("MembershipPolicy")]
    public virtual ICollection<User> Users { get; set; } = new List<User>();
}