// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("MembershipHistory")]
public partial class MembershipHistory
{
    [Key]
    [Column("MembershipHistoryID")]
    public int MembershipHistoryId { get; set; }

    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(50)]
    public string OldMembershipLevel { get; set; }

    [StringLength(50)]
    public string NewMembershipLevel { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ChangeDate { get; set; }

    [StringLength(255)]
    public string Reason { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("MembershipHistories")]
    public virtual User User { get; set; }
}