// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("ProductSize")]
public partial class ProductSize
{
    [Key]
    [Column("ProductSizeID")]
    public int ProductSizeId { get; set; }

    [Column("ProductID")]
    public int? ProductId { get; set; }

    [Column("SizeID")]
    public int? SizeId { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductSizes")]
    public virtual Product Product { get; set; }

    [ForeignKey("SizeId")]
    [InverseProperty("ProductSizes")]
    public virtual Size Size { get; set; }
}