// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("ProductColor")]
public partial class ProductColor
{
    [Key]
    [Column("ProductColorID")]
    public int ProductColorId { get; set; }

    [Column("ProductID")]
    public int? ProductId { get; set; }

    [Column("ColorID")]
    public int? ColorId { get; set; }

    [StringLength(255)]
    public string ProductColorImage { get; set; }

    [ForeignKey("ColorId")]
    [InverseProperty("ProductColors")]
    public virtual Color Color { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductColors")]
    public virtual Product Product { get; set; }
}