// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("ProductImage")]
public partial class ProductImage
{
    [Key]
    [Column("ProductImageID")]
    public int ProductImageId { get; set; }

    [Column("ProductID")]
    public int? ProductId { get; set; }

    [Column("ImageID")]
    public int? ImageId { get; set; }

    [ForeignKey("ImageId")]
    [InverseProperty("ProductImages")]
    public virtual Image Image { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductImages")]
    public virtual Product Product { get; set; }
}