// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Rating")]
public partial class Rating
{
    [Key]
    [Column("RatingID")]
    public int RatingId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column("ProductID")]
    public int? ProductId { get; set; }

    [Column("FeedbackID")]
    public int? FeedbackId { get; set; }

    public int? RatingValue { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateGiven { get; set; }

    [ForeignKey("FeedbackId")]
    [InverseProperty("Ratings")]
    public virtual Feedback Feedback { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Ratings")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Ratings")]
    public virtual User User { get; set; }
}