// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

public partial class RentalOrderDetail
{
    [Key]
    [Column("OrderDetailsID")]
    public int OrderDetailsId { get; set; }

    [Column("OrderID")]
    public int? OrderId { get; set; }

    [Column("ProductID")]
    public int? ProductId { get; set; }

    public int? Quantity { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RentalStart { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RentalEnd { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DueDate { get; set; }

    [StringLength(50)]
    public string RentalOrderDetailsColor { get; set; }

    [StringLength(50)]
    public string RentalOrderDetailsSize { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("RentalOrderDetails")]
    public virtual RentalOrder Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("RentalOrderDetails")]
    public virtual Product Product { get; set; }
}