// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

public partial class RewardPoint
{
    [Key]
    [Column("RewardPointsID")]
    public int RewardPointsId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    public int? Points { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastUpdated { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("RewardPointsNavigation")]
    public virtual User User { get; set; }
}