// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("RewardRedemption")]
public partial class RewardRedemption
{
    [Key]
    [Column("RewardRedemptionID")]
    public int RewardRedemptionId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    public int? PointsRedeemed { get; set; }

    [StringLength(255)]
    public string RedemptionDescription { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RedemptionDate { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("RewardRedemptions")]
    public virtual User User { get; set; }
}