// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("Token")]
public partial class Token
{
    [Key]
    [Column("TokenID")]
    public int TokenId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }

    [Column(TypeName = "text")]
    public string AccessToken { get; set; }

    [Column(TypeName = "text")]
    public string RefreshToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? IssuedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ExpiresAt { get; set; }

    [StringLength(10)]
    public string Status { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Tokens")]
    public virtual User User { get; set; }
}