// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EXE201.DAL.Models;

[Table("User")]
public partial class User
{
    [Key]
    [Column("UserID")]
    public int UserId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UserName { get; set; }

    [StringLength(100)]
    public string FullName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Password { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string Phone { get; set; }

    public int? Gender { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string ProfileImage { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string UserStatus { get; set; }

    [StringLength(255)]
    public string Address { get; set; }

    [StringLength(50)]
    public string MembershipLevel { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? TotalRentalValue { get; set; }

    public int? RewardPoints { get; set; }

    [Column("MembershipPolicyID")]
    public int? MembershipPolicyId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LastMembershipUpdate { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    [InverseProperty("User1")]
    public virtual ICollection<Conversation> ConversationUser1s { get; set; } = new List<Conversation>();

    [InverseProperty("User2")]
    public virtual ICollection<Conversation> ConversationUser2s { get; set; } = new List<Conversation>();

    [InverseProperty("User")]
    public virtual ICollection<Deposit> Deposits { get; set; } = new List<Deposit>();

    [InverseProperty("User")]
    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    [InverseProperty("User")]
    public virtual ICollection<MembershipHistory> MembershipHistories { get; set; } = new List<MembershipHistory>();

    [ForeignKey("MembershipPolicyId")]
    [InverseProperty("Users")]
    public virtual MembershipPolicy MembershipPolicy { get; set; }

    [InverseProperty("Sender")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    [InverseProperty("User")]
    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    [InverseProperty("User")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("User")]
    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    [InverseProperty("User")]
    public virtual ICollection<RentalOrder> RentalOrders { get; set; } = new List<RentalOrder>();

    [InverseProperty("User")]
    public virtual ICollection<RewardPoint> RewardPointsNavigation { get; set; } = new List<RewardPoint>();

    [InverseProperty("User")]
    public virtual ICollection<RewardRedemption> RewardRedemptions { get; set; } = new List<RewardRedemption>();

    [InverseProperty("User")]
    public virtual ICollection<Token> Tokens { get; set; } = new List<Token>();

    [InverseProperty("User")]
    public virtual ICollection<VerifyCode> VerifyCodes { get; set; } = new List<VerifyCode>();

    [ForeignKey("UserId")]
    [InverseProperty("Users")]
    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}